const API_BASE_URL_DEVELOPMENT = 'https://localhost:7172/api/customers'
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net'

const ENDPOINTS = 
{
    GET_ALL_CUSTOMERS: 'allCustomers',
    UPDATE_CUSTOMER: 'edit/',
    CREATE_CUSTOMER: 'create',

};

const development = {
    API_URL_GET_ALL_CUSTOMERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_CUSTOMERS}`,
    API_URL_UPDATE_CUSTOMER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_CUSTOMER}`,
    API_URL_CREATE_CUSTOMER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_CUSTOMER}`,
    API_URL_DELETE_CUSTOMER: `${API_BASE_URL_DEVELOPMENT}/`
};

const production = {
    API_URL_GET_ALL_CUSTOMERS: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_CUSTOMERS}`,
    API_URL_UPDATE_CUSTOMER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_CUSTOMER}`,
    API_URL_CREATE_CUSTOMER: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_CUSTOMER}`,
    API_URL_DELETE_CUSTOMER: `${API_BASE_URL_PRODUCTION}/`
};

const Constants = process.env.NODE_ENV === 'development' ? development : production

export default Constants;
